# Generated by Django 3.0.1 on 2020-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', models.CharField(max_length=200)),
                ('pubchemId', models.CharField(max_length=200)),
                ('drugName', models.CharField(max_length=200)),
                ('pmid', models.CharField(max_length=200)),
                ('approvedAgainstDiseases', models.CharField(blank=True, max_length=2000)),
                ('geneTargets', models.CharField(max_length=200)),
                ('uniportId', models.CharField(max_length=200)),
                ('geneSymbol', models.CharField(max_length=200)),
            ],
        ),
    ]
