# Generated by Django 3.0.1 on 2020-12-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
